create table produto (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    tipo varchar(20) not null
);

create table variacao (
    id bigint generated by default as identity primary key,
    produto_id bigint not null references produto (id),
    nome varchar(255) not null,
    reserva_seguranca integer not null default 0
);

create table composicao_kit (
    id bigint generated by default as identity primary key,
    kit_variacao_id bigint not null references variacao (id),
    variacao_base_id bigint not null references variacao (id),
    quantidade integer not null
);

create table movimentacao (
    id bigint generated by default as identity primary key,
    variacao_id bigint not null references variacao (id),
    data date not null,
    tipo varchar(20) not null,
    quantidade integer not null
);

create table encomenda_producao (
    id bigint generated by default as identity primary key,
    variacao_id bigint not null references variacao (id),
    quantidade integer not null,
    data_prevista date,
    status varchar(20) not null
);

create table pedido_reservado (
    id bigint generated by default as identity primary key,
    variacao_id bigint not null references variacao (id),
    quantidade integer not null,
    data_venda date,
    status varchar(20) not null
);

create index idx_variacao_produto_id on variacao (produto_id);
create index idx_movimentacao_variacao_id on movimentacao (variacao_id);
create index idx_movimentacao_data on movimentacao (data);
create index idx_encomenda_producao_variacao_id_status on encomenda_producao (variacao_id, status);
create index idx_pedido_reservado_variacao_id_status on pedido_reservado (variacao_id, status);
create index idx_composicao_kit_kit_variacao_id on composicao_kit (kit_variacao_id);
